### ISSUE TITLE
Setup PI to be an alternate git remote

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/infrastructure#69]
In the spirit of *digital homesteading*, I would like to self host my git repositories. **GitHub** is way over-featured for what I really need. I may keep using it as a mirror until I have a public interface on top of what I implement here.

I will continue to use **GitHub Issues**.

# Done When

- [x] `infrastructure` is pushed
- [x] `presentations` is pushed
- [x] `tabularasa` is pushed
- [x] `scottmuc.github.com` is migrated to `scottmuc.com`
- [x] `dns-zone-blocklist` is pushed
- [x] A commit and push workflow is figured out

## Out of Scope

- `devopsbookmarks.com` will remain as is... I may try and transfer ownership of it

**Comment by scottmuc** [comment]
# First Attempt

```
~/workspace/infrastructure ? git remote add pi git@pi:scottmuc/infrastructure.git

~/workspace/infrastructure ? git push pi HEAD
Enumerating objects: 5184, done.
Counting objects: 100% (5184/5184), done.
Delta compression using up to 12 threads
Compressing objects: 100% (2061/2061), done.
Writing objects: 100% (5184/5184), 3.28 MiB | 12.50 MiB/s, done.
Total 5184 (delta 3022), reused 4826 (delta 2807), pack-reused 0
remote: Resolving deltas: 100% (3022/3022), done.
To pi:scottmuc/infrastructure.git
 * [new branch]      HEAD -> main
 * 
~/workspace/infrastructure ? git lla -2
* ff887e5 (HEAD -> main, pi/main) Add background color "smarts" to nvim config
* 87be352 (origin/main, origin/HEAD) Ditching delta
```

The 0b90dda commit adds the functionality that enables the above commands to work. Some noteworthy configuration to reflect on is:

* The `git` users home directory is `/mnt/vcapstore/repos` so I don't have to fully qualify the repo path on the remote.
* Normalizing on a host name so that my remote references can work away from home would be useful.
* I would prefer to have the `git` user in `/home`, so I may need to symlink so this config can survive a repave.
* Do I need an "org" path if it's my server? `git@git.scottmuc.com:/scottmuc/scottmuc.com.git` feels a bit... repetitive :D

**Comment by scottmuc** [comment]
# Summary

This was easier than I thought to implement this. It's given me enough information to ponder how I want to go forward with this. For now I'm happy with my `pi` being a lagging mirror of what's on **GitHub**.

To keep my mirror up-to-date, I can run the following:

```
cd
mr update
mr run git push pi HEAD
```

That being said, my PC and laptop are also mirrors. The goal here is to self-host `origin` at some point. When repaving the PI, I'll need to add instructions to ensure latest code is fetched since `origin` will technically be down when doing the repave :).

# Todo (for another time)

* setup `git` user in a way that survives repaves
* review repo names and folders in a world where they don't need to distinguish themselves for the world
* setup a split DNS for `git.scottmuc.com`
* revisit remotes, perhaps `origin` is the PI and `github` is the mirror
* explore what type of web UI I might want to present on top of these repos
* explore issue tracking (the public issues is something I 100% want to continue doing)
